# Generated by Django 3.0.7 on 2020-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20200701_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='100x60.jpg', upload_to='company_images'),
        ),
    ]
